name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: gok24code
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Set outputs as environment file
        run: |
          echo "GIF_PATH=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV
          echo "SVG_PATH=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV
      - run: git status
      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: false
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
